<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup Label="Ploch sibling libraries (source)" Condition="'$(UsePlochProjectReferences)' == 'true'">
        <ProjectReference Include="$(PlochSiblingsRoot)ploch-data\src\Data.Model\Ploch.Data.Model.csproj" />
    </ItemGroup>
    <ItemGroup Label="Ploch libraries (NuGet)" Condition="'$(UsePlochProjectReferences)' != 'true'">
        <PackageReference Include="Ploch.Data.Model" />
    </ItemGroup>
</Project>
