<Project>
    <ItemGroup>
        <PackageVersion Include="Spectre.Console" Version="0.54.0" />
        <PackageVersion Include="Spectre.Console.Analyzer" Version="1.0.0" />
        <PackageVersion Include="Spectre.Console.Cli" Version="0.53.1" />
        <PackageVersion Include="Spectre.Console.ImageSharp" Version="0.54.0" />
    </ItemGroup>
</Project>
