name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo "The branch name is ${{ github.repository }}"
      - uses: actions/checkout@v3
      - name: Verify Markdown files
        id: write-good
        uses: tomwhross/write-good-action@v1.6
